(linenum) @tag
(fn_name) @function
(comment_text) @comment

(integer) @number
(real) @number
(string) @string
(terminal_string) @string
(literal) @string
(data_real) @number
(data_integer) @number

(svar) @variable
(string_array) @variable
(realvar) @variable
(real_scalar) @variable
(real_array) @variable
(intvar) @variable
(int_scalar) @variable
(int_array) @variable

(rem_tok) @comment
(plus_tok) @operator
(minus_tok) @operator
(times_tok) @operator
(div_tok) @operator
(pow_tok) @operator
(gtr_tok) @operator
(eq_tok) @operator
(less_tok) @operator
(and_tok) @operator
(or_tok) @operator
(not_tok) @operator
(end_tok) @keyword.builtin
(for_tok) @keyword.builtin
(next_tok) @keyword.builtin
(data_tok) @keyword.builtin
(input_tok) @keyword.builtin
(del_tok) @keyword.builtin
(dim_tok) @keyword.builtin
(read_tok) @keyword.builtin
(gr_tok) @keyword.builtin
(text_tok) @keyword.builtin
(prn_tok) @keyword.builtin
(inn_tok) @keyword.builtin
(call_tok) @keyword.builtin
(plot_tok) @keyword.builtin
(hlin_tok) @keyword.builtin
(vlin_tok) @keyword.builtin
(hgr2_tok) @keyword.builtin
(hgr_tok) @keyword.builtin
(hcoloreq_tok) @keyword.builtin
(hplot_tok) @keyword.builtin
(draw_tok) @keyword.builtin
(xdraw_tok) @keyword.builtin
(htab_tok) @keyword.builtin
(home_tok) @keyword.builtin
(roteq_tok) @keyword.builtin
(scaleeq_tok) @keyword.builtin
(shload_tok) @keyword.builtin
(trace_tok) @keyword.builtin
(notrace_tok) @keyword.builtin
(normal_tok) @keyword.builtin
(inverse_tok) @keyword.builtin
(flash_tok) @keyword.builtin
(coloreq_tok) @keyword.builtin
(pop_tok) @keyword.builtin
(vtab_tok) @keyword.builtin
(himem_tok) @keyword.builtin
(lomem_tok) @keyword.builtin
(onerr_tok) @keyword.builtin
(resume_tok) @keyword.builtin
(recall_tok) @keyword.builtin
(store_tok) @keyword.builtin
(speedeq_tok) @keyword.builtin
(let_tok) @keyword.builtin
(goto_tok) @keyword.builtin
(run_tok) @keyword.builtin
(if_tok) @keyword.builtin
(restore_tok) @keyword.builtin
(amp_tok) @keyword.builtin
(gosub_tok) @keyword.builtin
(return_tok) @keyword.builtin
(stop_tok) @keyword.builtin
(on_tok) @keyword.builtin
(wait_tok) @keyword.builtin
(load_tok) @keyword.builtin
(save_tok) @keyword.builtin
(def_tok) @keyword.builtin
(poke_tok) @keyword.builtin
(print_tok) @keyword.builtin
(cont_tok) @keyword.builtin
(list_tok) @keyword.builtin
(clear_tok) @keyword.builtin
(get_tok) @keyword.builtin
(new_tok) @keyword.builtin
(tabp_tok) @keyword.builtin
(to_tok) @keyword.builtin
(fn_tok) @keyword.builtin
(spcp_tok) @keyword.builtin
(then_tok) @keyword.builtin
(at_tok) @keyword.builtin
(step_tok) @keyword.builtin
(sgn_tok) @function.builtin
(int_tok) @function.builtin
(abs_tok) @function.builtin
(usr_tok) @function.builtin
(fre_tok) @function.builtin
(scrnp_tok) @function.builtin
(pdl_tok) @function.builtin
(pos_tok) @function.builtin
(sqr_tok) @function.builtin
(rnd_tok) @function.builtin
(log_tok) @function.builtin
(exp_tok) @function.builtin
(cos_tok) @function.builtin
(sin_tok) @function.builtin
(tan_tok) @function.builtin
(atn_tok) @function.builtin
(peek_tok) @function.builtin
(len_tok) @function.builtin
(str_tok) @function.builtin
(val_tok) @function.builtin
(asc_tok) @function.builtin
(chr_tok) @function.builtin
(left_tok) @function.builtin
(right_tok) @function.builtin
(mid_tok) @function.builtin
